  version: "3.1"
  
  services:

    sonar:
      image: sonarqube
      restart: on-failure
      ports:
        - "9100:9000"
      volumes:
        - ./volumes/sonar_conf:/opt/sonarqube/conf
        - ./volumes/sonar_data:/opt/sonarqube/data
        - ./volumes/sonar_logs:/opt/sonarqube/logs
        - ./volumes/sonar_extensions:/opt/sonarqube/extensions

        