  version: "3.1"
  
  services:

    db:
      image: mariadb
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: mydb
      ports:
        - "3308:3306"
      volumes:
        - db_vol:/var/lib/mysql
        - ./volumes/db_initializing_queries:/docker-entrypoint-initdb.d

  volumes:
    db_vol:
